Repository git-lfs/git-lfs, pull requests merged in 2018-02, with the labels that each got.

#2851 prune: always prune excluded paths
  commands/command_prune.go
Labels: bug, review

#2883 *: fix 32-bit alignment issues with `sync/atomic`
  git/odb/object_db.go
  git/odb/object_writer.go
  lfsapi/stats.go
  tasklog/percentage_task.go
Labels: bug

#2884 git/githistory: copy entries from cache, elsewhere
  git/githistory/rewriter.go
Labels: bug, review

#2875 filepathfilter: implement using wildmatch
  commands/command_migrate_import.go
  filepathfilter/bench_test.go
  filepathfilter/filepathfilter.go
  filepathfilter/filepathfilter_test.go
  git/githistory/fixtures_test.go
  git/githistory/rewriter.go
  git/githistory/rewriter_test.go
  glide.lock
  glide.yaml
  lfs/util.go
  test/test-migrate-import.sh
  tools/filetools.go
  tools/filetools_test.go
  vendor/github.com/git-lfs/wildmatch/.travis.yml
  vendor/github.com/git-lfs/wildmatch/LICENSE.md
  vendor/github.com/git-lfs/wildmatch/README.md
  vendor/github.com/git-lfs/wildmatch/package.go
  vendor/github.com/git-lfs/wildmatch/wildmatch.go
  vendor/github.com/git-lfs/wildmatch/wildmatch_linux.go
  vendor/github.com/git-lfs/wildmatch/wildmatch_notlinux.go
  vendor/github.com/git-lfs/wildmatch/wildmatch_test.go
Labels: review

#2888 test: add wildmatch migration tests
  test/test-migrate-import.sh
Labels: bug, review

#2889 filepathfilter: test correct set of global wildcards
  filepathfilter/filepathfilter_test.go
Labels: bug, review

#2890 README.md: hotlink to the Limitations wiki page from README
  README.md
Labels: review
