Repository git-lfs/git-lfs, pull requests merged in 2018-07, with the labels that each got.

#3099 lfsapi/ssh.go: use zero-value sentinels
  lfsapi/ssh.go
Labels: bug

#3098 config/config.go: case-insensitive error search
  config/config.go
Labels: bug

#3109 change lfs.allowincompletepush default from true to false
  commands/uploader.go
  docs/man/git-lfs-config.5.ronn
  test/test-pre-push.sh
  test/test-push-failures-local.sh
  test/test-push-failures-remote.sh
  test/test-push-missing.sh
  test/test-push.sh
Labels: discussion

#3116 fs: support multiple object alternates
  config/config.go
  fs/fs.go
  lfs/lfs.go
  test/test-alternates.sh
  test/test-env.sh
  test/test-worktree.sh
Labels: bug

#3117 fs/fs.go: support alternates from environment variable
  config/config.go
  fs/fs.go
  test/test-alternates.sh
  test/testhelpers.sh
Labels: enhancement

#3113 config/git_fetcher.go: mark 'lfs.allowincompletepush' as safe
  config/git_fetcher.go
Labels: enhancement

#3124 commands: warn if working copy is dirty
  commands/command_migrate.go
  commands/command_migrate_export.go
  commands/command_migrate_import.go
  git/git.go
  test/test-migrate-export.sh
  test/test-migrate-fixtures.sh
  test/test-migrate-fixup.sh
  test/test-migrate-import-no-rewrite.sh
  test/test-migrate-import.sh
Labels: enhancement

#3144 Makefile: replace many scripts with make targets
  CONTRIBUTING.md
  Makefile
  appveyor.yml
  debian/rules
  rpm/SPECS/git-lfs.spec
  rpm/build_rpms.bsh
  script/bootstrap
  script/build.go
  script/cibuild
  script/fmt
  script/genmakefile/genmakefile.go
  script/install.sh
  script/lint
  script/man
  script/release
  script/release.go
  script/run
  script/script.go
  script/test
  script/update-version
  script/vendor
  t/testhelpers.sh
Labels: review

#3150 release: v2.5.0
  CHANGELOG.md
  config/version.go
  debian/changelog
  rpm/SPECS/git-lfs.spec
  versioninfo.json
Labels: release

#3152 config: add origin to remote list
  commands/command_env.go
  config/config.go
  t/t-env.sh
  t/t-pull.sh
Labels: bug

#3153 Makefile: list prerequisites for resource.syso
  Makefile
Labels: bug

#3155 script/install.sh: mark as executable
  script/install.sh
Labels: bug
