Repository git-lfs/git-lfs, pull requests merged in 2018-10, with the labels that each got.

#3296 Checkout options for conflicts
  commands/command_checkout.go
  commands/pull.go
  docs/man/git-lfs-checkout.1.ronn
  git/git.go
  t/t-checkout.sh
Labels: review

#3298 all: use Go 1.11.1 in CI
  .travis.yml
  appveyor.yml
Labels: review

#3304 Honor umask and core.sharedRepository
  config/config.go
  config/config_test.go
  config/util_nix.go
  config/util_windows.go
  lfs/extension.go
  lfs/gitfilter_clean.go
  lfs/util.go
  t/t-umask.sh
Labels: bug

#3290 RFC: SSH protocol
  docs/proposals/ssh_adapter.md
Labels: proposal, wip

#3325 CONTRIBUTING.md: :nail_care:
  CONTRIBUTING.md
Labels: review
