Repository git-lfs/git-lfs, pull requests merged in 2018-08, with the labels that each got.

#3163 tq: make Content-Type detection disable-able
  docs/man/git-lfs-config.5.ronn
  errors/types.go
  lfsapi/errors.go
  t/t-content-type.sh
  t/t-push-failures-remote.sh
  tq/basic_upload.go
  tq/transfer_queue.go
Labels: bug, enhancement

#3160 Makefile: add explicit rule for commands/mancontent_gen.go
  Makefile
Labels: bug

#3168 docs/man/mangen.go: don't show non-fatal output without --verbose
  docs/man/mangen.go
Labels: review

#3169 release: v2.5.1
  CHANGELOG.md
  config/version.go
  debian/changelog
  rpm/SPECS/git-lfs.spec
  versioninfo.json
Labels: release

#3190 locks: manage write permissions of ignored files
  locking/lockable.go
  t/t-lock.sh
  tools/filetools.go
  tools/filetools_test.go
Labels: bug, review

#3212 config: expand core.hooksPath
  commands/commands.go
  config/config.go
  t/t-install-custom-hooks-path.sh
  tools/filetools.go
  tools/filetools_test.go
Labels: bug

#3218 go.mod: pin github.com/git-lfs/wildmatch to v1.0.0
  go.mod
  go.sum
  vendor/github.com/git-lfs/wildmatch/.travis.yml
  vendor/github.com/git-lfs/wildmatch/go.mod
  vendor/modules.txt
Labels: review
