Repository git-lfs/git-lfs, pull requests merged in 2019-02, with the labels that each got.

#3501 commands/command_pointer.go: introduce `--check` option
  commands/command_pointer.go
  docs/man/git-lfs-pointer.1.ronn
  t/t-pointer.sh
Labels: review

#3509 docs/man/git-lfs-config.5.ronn: document GIT_LFS_SKIP_SMUDGE
  docs/man/git-lfs-config.5.ronn
  docs/man/git-lfs-filter-process.1.ronn
  docs/man/git-lfs-smudge.1.ronn
Labels: review

#3513 t/t-smudge.sh: remove unnecessary test
  t/t-smudge.sh
Labels: bug, review, test-failure, tests

#3514 .circleci: don't use 'brew prune'
  .circleci/config.yml
Labels: review, tests

#3492 git/version.go: replace sync.Mutex usage with sync.Once
  git/version.go
Labels: review

#3520 release: v2.7.0
  CHANGELOG.md
  config/version.go
  debian/changelog
  rpm/SPECS/git-lfs.spec
  versioninfo.json
Labels: release

#3542 release: v2.7.1
  CHANGELOG.md
  config/version.go
  debian/changelog
  docs/howto/release-git-lfs.md
  rpm/SPECS/git-lfs.spec
  script/upload
  tq/basic_download.go
  tq/basic_upload.go
  versioninfo.json
Labels: release
